name: Send DingTalk Notification

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟执行一次
  workflow_dispatch: # 手动触发

permissions:
  contents: read

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Send DingTalk Message
        env:
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        run: python send_dingtalk.py
